# -*- coding: utf-8 -*-
"""Deteccao_Fraude.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5iwmjYSv-gQ1lkSUxe9oGPfEgoFeD4u

# Detecção de Fraude em Transações
"""

import pandas as pd

url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"

df = pd.read_csv(url)

df.head()

"""# Problema de Classificação Desbalanceada

Fraudes são raras -> modelo pode ignorar a classe 1.
"""

df["Class"].value_counts(normalize = True)

"""# Feature Engineering

Criamos variáveis que ajudam o modelo.
"""

import numpy as np

df['Amount_log'] = np.log(df['Amount'] + 1)

df.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df['Amount_scaled'] =  scaler.fit_transform(df['Amount'].values.reshape(-1, 1))

df.head()

from re import X
from sklearn.model_selection import train_test_split

X = df.drop("Class", axis = 1)
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

"""# Logistic Regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# 1. Normalizar os dados (essencial para o algoritmo convergir corretamente)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 2. Criar e treinar o modelo com os dados escalados
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

# 3. Fazer as previsões usando os dados de teste também escalados
y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""Accuracy pode ser alta mesmo sem detetar fraudes.

Por isso usamos:
* Recall (mais importante)
* Precision
* F1-score
"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_probs = model.predict_proba(X_test_scaled)[:, 1]

fpr, tpr, _ = roc_curve(y_test, y_probs)

plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

print("AUC:", roc_auc_score(y_test, y_probs))

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_test, y_probs)

plt.plot(recall, precision)
plt.title("Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

"""# Balanceamento de Dados"""

# Undersampling
fraudes = df[df["Class"] == 1]
normais = df[df["Class"] == 0].sample(len(fraudes), random_state=42)

df_under = pd.concat([fraudes, normais])

# Oversampling
from imblearn.over_sampling import SMOTE

smote = SMOTE()

X_res, y_res = smote.fit_resample(X, y)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

threshold = 0.3

y_pred_custom = (y_probs > threshold).astype(int)

print(classification_report(y_test, y_pred_custom))

"""# Modelo Avançado - XGBoost

**XGBoost** é um dos algoritmos mais usados em competições e mercado.
Ele é o mais poderoso que ***Random Forest*** para muitos problemas.
"""

from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight=10,  # ajuda com desbalanceamento
    use_label_encoder=False,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print(classification_report(y_test, y_pred_xgb))

"""# Importância das variáveis
Ajuda a entender quais variáveis influenciam mais o modelo.
"""

import matplotlib.pyplot as plt

importancias = xgb.feature_importances_

plt.bar(range(len(importancias)), importancias)
plt.title("Importância das variáveis")
plt.show()

"""# Ajuste de hiperparâmetros
Testamos várias combinações para melhorar o modelo.
"""

from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth": [3, 5],
    "n_estimators": [50, 100]
}

grid = GridSearchCV(
    XGBClassifier(eval_metric="logloss"),
    param_grid,
    scoring="recall",
    cv=3
)

grid.fit(X_train, y_train)

print("Melhor modelo:", grid.best_params_)

"""# Explicabilidade (SHAP)

***SHAP*** mostra como cada variável influencia a decisão do modelo.
"""

import shap

# 1. Utilizar o TreeExplainer otimizado para modelos baseados em árvores
explainer = shap.TreeExplainer(xgb)

# 2. Calcular os valores SHAP (se for muito pesado para 100 amostras, podes reduzir)
shap_values = explainer(X_test[:100])

# 3. Gerar o gráfico de barras
shap.plots.bar(shap_values)